spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql@1234
    url: jdbc:mysql://localhost:3306/Data_Collection
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
